spring:
  application:
    name: "BeeStay-CyberKnight-BackEnd"
  datasource:
    url: jdbc:sqlserver://beestay.database.windows.net:1433;databaseName=beestay;encrypt=false;trustServerCertificate=True
    username: beestay@beestay
    password: Sa@123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB